### ISSUE TITLE
hello,i meet two error,how can i do

### ISSUE THREAD

**Issue by Helium65** [Freeloot/Discord-MassDM#1]
ERROR: Could not find a version that satisfies the requirement discord (from versions: none)
ERROR: No matching distribution found for discord

**Comment by freeloot** [comment]
try upgrading your version of pip
https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494#49748494

**Comment by freeloot** [comment]
> ERROR: Could not find a version that satisfies the requirement discord (from versions: none) ERROR: No matching distribution found for discord

try upgrading your version of pip
https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494#49748494
